### ISSUE TITLE
Flaky test: `TestGatewayEssentials`

### ISSUE THREAD

**Issue by pmalek** [Kong/gateway-operator#197]
The following failure has been observed in this CI run: https://github.com/Kong/gateway-operator/runs/7970955157?check_suite_focus=true#step:5:3743

```    gateway_test.go:99: 
        	Error Trace:	/home/runner/work/gateway-operator/gateway-operator/test/integration/gateway_test.go:99
        	Error:      	Condition never satisfied
        	Test:       	TestGatewayEssentials
```

The test succeeded on a subsequent run without any code modifications: https://github.com/Kong/gateway-operator/runs/7971300586?check_suite_focus=true

**Comment by pmalek** [comment]
Second failure in https://github.com/Kong/gateway-operator/runs/7971753639?check_suite_focus=true#step:5:4631

**Comment by shaneutt** [comment]
Saw it again here: https://pipelines.actions.githubusercontent.com/serviceHosts/c81d839e-81ff-4819-b743-a1ded9d25776/_apis/pipelines/1/runs/2022/signedlogcontent/2?urlExpires=2022-08-23T15%3A07%3A15.9979174Z&urlSigningMethod=HMACV1&urlSignature=dMOfZTomyII2r7JIU4YCYXCGryE3qJUzd9BuTsvAY84%3D

After debugging, I'm pretty sure #91 introduced the flake because the 10 seconds we used to wait is not enough now that we're deleting and replacing the `DataPlane` just before. My suspicion is that a slight rework of the test to allow more time during these steps will be adequate, I'll create a patch.

**Comment by pmalek** [comment]
> Saw it again here: https://pipelines.actions.githubusercontent.com/serviceHosts/c81d839e-81ff-4819-b743-a1ded9d25776/_apis/pipelines/1/runs/2022/signedlogcontent/2?urlExpires=2022-08-23T15%3A07%3A15.9979174Z&urlSigningMethod=HMACV1&urlSignature=dMOfZTomyII2r7JIU4YCYXCGryE3qJUzd9BuTsvAY84%3D

Weird URL 🤔 And it says `{"count":11,"value":"Uri expired"}`

> After debugging, I'm pretty sure https://github.com/Kong/gateway-operator/pull/91 introduced the flake because we now delete and try to have the DataPlane re-created during TestGatewayEssentials. I'm going to verify whether the DataPlane is simply not given enough time, OR if it's actually perma-crashed.

Oh, nice. Thanks!

**Comment by shaneutt** [comment]
After some debugging, it appears the replacement functionality is flaking. I've temporarily disabled this in https://github.com/Kong/gateway-operator/pull/210 and this issue is prioritized to get this fixed and re-enable the tests before the next release.

**Comment by pmalek** [comment]
Yup, it seems that #207 didn't solve it completely. Another failure: https://github.com/Kong/gateway-operator/runs/7978283717?check_suite_focus=true#step:5:4679

**Comment by shaneutt** [comment]
The tests have been temporarily disabled, closing this in favor of https://github.com/Kong/gateway-operator/issues/212 which includes the scope of this and https://github.com/Kong/gateway-operator/issues/199 and will be resolved for the next release.
