### ISSUE TITLE
Special-case "Immutable" EnvVars for ControlPlanes

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#65]
### Problem Statement

Currently we allow end-users to specify _all_ env vars for the control plane, but there are some values that should not be usable when defining the SPEC:

- `CONTROLLER_PUBLISH_SERVICE`
- `CONTROLLER_KONG_ADMIN_URL`
- `CONTROLLER_LEADER_ELECT`
- `CONTROLLER_KONG_ADMIN_TLS_CLIENT_CERT`
- `CONTROLLER_KONG_ADMIN_TLS_CLIENT_CERT_FILE`
- `CONTROLLER_KONG_ADMIN_TLS_CLIENT_KEY`
- `CONTROLLER_KONG_ADMIN_TLS_CLIENT_KEY_FILE`

This list is non-exhaustive, but the commonality is that these are all values that the relevant controller is responsible for dynamically determining and the controller's dynamic value is paramount.

### Acceptance Criteria

- [ ] controller-determined ENV vars like `CONTROLLER_PUBLISH_SERVICE` are not allowed for usage by the validating webhook
- [ ] controller-determined ENV vars like `CONTROLLER_PUBLISH_SERVICE` are stripped out of the SPEC if found during reconcilation, and a (validation) error is logged
- [ ] status entries for the controller-determined values are added to indicate that they're not meant to be declared as part of the intended state, and are instead part of the observed state after automation provisions them

### Additional information

Determine the exhaustive list of options first, and then implement the validation and status fields for them.

**Comment by rainest** [comment]
Continuing from https://github.com/Kong/gateway-operator/pull/103#discussion_r929171841, we shouldn't do this. Users blindly overriding automatically-set variables without documentation instructing them to do so or a known reason that they do need to override is not a common occurrence, and while not unheard of, the fix is a quick "don't do that" support interaction.

We can't know every possible reason someone may want to override a value, but there are definitely cases where doing so makes sense, so we should keep the flexibility to allow them without code changes.

**Comment by shaneutt** [comment]
> Continuing from [#103 (comment)](https://github.com/Kong/gateway-operator/pull/103#discussion_r929171841), we shouldn't do this. Users blindly overriding automatically-set variables without documentation instructing them to do so or a known reason that they do need to override is not a common occurrence, and while not unheard of, the fix is a quick "don't do that" support interaction.
> 
> We can't know every possible reason someone may want to override a value, but there are definitely cases where doing so makes sense, so we should keep the flexibility to allow them without code changes.

I don't agree, but I'm open to being persuaded. Allowing the user to provide configuration that they _can't viably be responsible for themselves_ seems to serve only to cause confusion. Alternatively validation which denies its usage can clearly indicate to the user the reason why they shouldn't do this.

**Comment by rainest** [comment]
We should either log warnings for variables we don't usually expect users to override and/or document which we set by default and why, not disallow it outright.

One of the more enduring lessons from development of the chart is that someone will eventually need to override something (not just environment variables). In this case, allowing overrides across the board provides a lightweight way to allow this that does not impact the default path and requires intent and a fair amount of effort to actually break things.

Would we say that there's no case where a user security team would mandate use of a CA they control, and the user does the work to provision, mount, and use certificates issued by it? Doing so is clearly _viable_--users wouldn't be able to use this functionality without the operator otherwise--it's just more work. To another of the mentioned settings, are we telling users who chain another LoadBalancer proxy Service in front of Kong that they shouldn't be able to set the publish service, even though the proxy Service address is not what external clients need to access? Though not the majority, such configurations come up fairly often in discussions.

We do have settings that users cannot configure, e.g. `CONTROLLER_LEADER_ELECT` no longer exists exists except to say that it's a deprecated setting that has no effect (though, somewhat amusingly, I often want to restore it because it's difficult to run a debugger when it's enabled due to internal timeouts in controller-runtime), but that's a very particular case where we can clearly enumerate all options (it's either on or off, and the correct value can always be derived from the database setting we obtain from the admin API) and can remove it from the controller config surface entirely. Most other configuration has a wider set of options, and those choices often depend on the broader environment, not just information we can pull from the admin API.

If we do not restrict which variables you can override, how bad is the expected problem path or harm? By default, users still do not need to provide values for these settings: taking the simplest path results in a working configuration with the automated values set. To break an environment you would need to:
- Know the setting exists. Newer users usually won't until they find some reason to set it.
- Set it independent of any obvious reason to (documentation won't instruct you to set it, and whatever functionality it controls should be working correctly with the defaults).
- Set it without setting other things you need (e.g. for certificates if you override the path but do not add volume mounts for it).
- Lack sufficient troubleshooting knowledge to determine why your manual configuration is incomplete.

Resolution is then universally "don't set that, you don't need to" or "you actually do need to override this to support your use case, but you need to do something else too", and the latter case still requires that we either allow overrides or add additional code to automatically manage the setting for other use cases (which may be impossible or more work than we want to commit for an obscure use case). For the former, we shouldn't be so afraid of possible confusion if you've already gone outside the bounds of what the defaults and docs cover.

**Comment by shaneutt** [comment]
How do you feel about there being a setting to "unlock" locked options so as to keep the heavier guard rails (rather than logging warnings) but also not block the supposed inevitable case?

**Comment by rainest** [comment]
How much do you think you need it? How great of a risk of problem overrides do you expect, with how bad of an impact? I still strongly feel that we should be permissive by default if doing so does not preclude us from writing a happy default path.

IMO this is proactively enforcing restrictions to defeat a hypothetical problem. If we had observed frequent cases where users did override automatic settings in the chart and weren't able to determine the cause of the problem on their own, this would make more sense, but we haven't. We shouldn't assume by default that users will go out of their way to shoot themselves in the foot and furthermore miss the correlation between the gun in hand and their new foot hole.

Something like this should be introduced in response to an observed UX problem, not put in place to proactively avoid a hypothetical one. Predicting how users will fail to navigate an application is hard, and authors are in a uniquely bad position to do so: we know all the product innards and can't easily blank that knowledge from our minds, and are inclined to develop safeguards that make sense for someone who has that knowledge as such. A novice user doesn't know `CONTROLLER_KONG_ADMIN_TLS_CLIENT_CERT` exists; they aren't likely to try and set it.

A designated "I am expert user" toggle makes sense in scenarios where you have very technically naive users and need to guard against malicious third parties. Things like bypassing browser certificate validation or enabling Android developer mode do have multi-step processes that ask you to affirm you're doing something unsafe because malicious parties can instruct naive users to click through warnings, and succeed more often if the warning is not very obvious and/or if the path to clear it is obfuscated. Our user base is systems administrators, however, who we expect to have a higher level of knowledge around what TLS is and such. We shouldn't need the extra guardrail.

**Comment by shaneutt** [comment]
"Permissive by default" to me honestly feels like the antithesis to some of the primary design goals going into this operator. However, I see that you feel very strongly about this and probably wont be persuaded my way, so in the interest of saving time and because we've got plenty of time to experiment (we're not even in the first alpha yet) and change this later if we find it necessary, I'm going to take a flat hand approach and default to closing this for now. Closed as is "no priority" not closed as in "we could never reconsider".

**Comment by jrsmroz** [comment]
Some of our env values are generated. Like the `CONTROLLER_KONG_ADMIN_URL`, it's generated when dataplane name change . How do we even distinguish env var set by a user from a one generated by an operator?

**Comment by shaneutt** [comment]
We currently can only distinguish that _during reconciliation_, e.g. the reconciliation machinery can know at the moment it tries to set vars if the var was already set and is a different value than what was derived. And only partially: the value could in fact be old reconciliation data. Thus why it made sense to me to avoid confusion altogether and simply don't allow these values to be set. That way you can clearly delineate values generated by the controller vs values set manually, and the user gets a clear failure if they try to set things they don't control. Again though, given the contention I personally think it's OK to hold on this for now and allow for some time to see how these things play out in practice. We can revisit this in the review period before we try and move to beta.

**Comment by shaneutt** [comment]
Also to ensure that we do actually revisit this issue before beta, a relevant TODO item has been added to https://github.com/Kong/gateway-operator/issues/120
