### ISSUE TITLE
Automated Gateway mTLS

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#7]
### Problem Statement

The `ControlPlane` resource is capable of communicating with the exposed admin api of the `DataPlane` using [mutual TLS (mTLS)](https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/). The purpose of this task is to add automation that creates and manages this mTLS configuration for new instances of the `DataPlane`, and ensures that instances of `ControlPlanes` attached to those `DataPlane` resources can be consumers of those `Secrets` and communicate with the `DataPlane` via the underlying certificates.

### Acceptance Criteria

- [ ] when a `DataPlane` resource is created, mTLS credentials are generated for it by the dataplane-controller
- [ ] any `Deployments` created for a `DataPlane` resource are automatically configured with the mTLS credentials on their admin API listen server
- [ ] when a `ControlPlane` becomes attached to a `DataPlane`, it is configured with the mTLS credentials needed to securely authenticate with the admin API
- [ ] when a `ControlPlane` becomes detached from a `DataPlane` the mTLS credentials it had previously are dropped
- [ ] when a `DataPlane` resource is deleted, it's mTLS `Secrets` are deleted

### Additional Notes

- [ ] TODO comments which linked to this issue are removed once resolved

**Comment by rainest** [comment]
Some thoughts looking around this initially:

- Kubernetes provides a [standard CSR to certificate pipeline](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/), but it's a bit clunky. To use it, instances would generate a cert/key pair internally and a [CSR resource](https://pkg.go.dev/k8s.io/api/certificates/v1beta1#CertificateSigningRequest) from it. Signing requires a controller that watches for these resources, checks if it's approved, and issues a certificate if so. There are decent [example implementations](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#what-s-next) for parts of these. We'd then need to manually stuff the signed certificate and key into a Secret to mount on the Kong instances.
- [cert-manager](https://cert-manager.io/) avoids writing a signer/approver and Secret manager, but isn't standard and uses custom resources, so it's not compatible with something else that uses the standard CSR API.
- If we're implementing our own signer, and it's part of the same project as the application manager, is there any reason to actually create the CSR resources? We can just pass the structs around internally.
- Do we have approval criteria beyond matching our signer name? If we _do_ use CSRs, have the same CA for both issuing client certificates _and_ server certificates, what's to stop a malicious application from either stealing secrets out of the config blob or impersonating a control plane? The model seems predicated on manual credential creation and distribution. Short circuiting the actual CSR resource does essentially avoid this, however, since there's no longer any way to actually request a certificate.

I'd like to be able to import the example signer more or less as-is internally, but it doesn't look like it exposes an external interface that'd let us avoid its normal API server interactions, so we probably need to vendor bits of the code.

**Comment by shaneutt** [comment]
Talked with Travis about the above comment in a zoom: I'm in favor of the approach where we manage a private CA belonging to the operator for the initial purposes of mTLS auth setup as this covers our immediate needs and has the least attack vectors of the proposed options.
