### ISSUE TITLE
Update dataplane env vars in controlplane when dataplane service changes

### ISSUE THREAD

**Issue by mlavacca** [Kong/gateway-operator#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The `ControlPlane` deployments are pointed to the correct `DataPlane` service via 2 different env vars: `CONTROLLER_PUBLISH_SERVICE`, and `CONTROLLER_KONG_ADMIN_URL`. These 2 vars contain the correct dataplane service address to talk to. With https://github.com/Kong/gateway-operator/pull/91, when the `DataPlane` service is deleted, it is recreated automatically by the `dataplane-controller`; the problem is that the service name is not static, but created through the `generateName` field. Hence, every time the `DataPlane`service is recreated by the `dataplane-controller`, the `controlplane-controller` should also update the `ControlPlane` deployment env vars.

### Proposed Solution

We should trigger an update on the `controlplane-controller` every time the `DataPlane` service changes. To do so, we can watch the `Dataplane` services in the `controlplane-controller` and trigger a reconciliation loop every time an event occurs.

### Acceptance Criteria

- [ ] Every time the dataplane service is created, the dataplane service env vars are set in the controlplane deployment
- [ ] Every time the dataplane service is deleted, the dataplane service env vars are unset from the controlplane deployment

**Comment by rainest** [comment]
Are we in position to actually work on this? It looks like the status of #91 is unclear until it's refactored around unrelated reconcile updates, and it doesn't look like it makes sense to handle this without #91 merged.

I opened https://github.com/Kong/gateway-operator/pull/130 into #91's branch since I figure the approach will be similar despite needs to refactor, and because we may as well get an answer on the environment update question.

**Comment by rainest** [comment]
Do we want to allow direct edits to the ControlPlane Deployment environment or require that you always update the ControlPlane?

To handle this we can either compare the _entire_ environment from the current ControlPlane Deployment against the environment generated by the latest run of the ControlPlane reconciler and update the Deployment with the latter if they differ, or we can surgically find the publish service variable and update only that one.

Updating the whole thing wipes out any user changes made directly to the Deployment, but I think that's okay since we intend for them to edit the environment via the ControlPlane. It solves the issue of not having the latest value for every generated value in the environment, current and future alike. Surgical edits only fix publish service, and would maybe be a bit annoying to handle for individual keys if we need to update a lot (maybe--right now I've implemented it by looping over the desired environment and then have a nested loop over the actual environment, but we probably could build something that transforms envar slices to and from maps to have only a single loop).

**Comment by mlavacca** [comment]
> Do we want to allow direct edits to the ControlPlane Deployment environment or require that you always update the ControlPlane?

I think that we should allow only updates on the controlplane object. The controlplane deployment is owned by the controlplane controller and it should be in charge of enforcing the expected spec.

> To handle this we can either compare the entire environment from the current ControlPlane Deployment against the environment generated by the latest run of the ControlPlane reconciler and update the Deployment with the latter if they differ, or we can surgically find the publish service variable and update only that one.

I vote for wiping out every change made by the user on the deployment spec and enforcing the deployment spec as it is intended to be by the controller (the user can customize the controlplane object to perform controlplane deployment customizations). I think that only labels and annotations should be modifiable by the user.
